// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.ML.Data;
using Microsoft.OpenApi.Models;
using SentimentModel_WebApi.Contracts;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<SentimentModel.ModelInput, SentimentModel.ModelOutput>()
    .FromFile("SentimentModel.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}


// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<SentimentModel.ModelInput, SentimentModel.ModelOutput> predictionEnginePool, CommentInput comment) =>
    //await Task.FromResult(predictionEnginePool.Predict(input)));
    {
        // map user input -> model input
        var modelInput = new SentimentModel.ModelInput
        {
            Col0 = comment.Text
        };

        var result = predictionEnginePool.Predict(modelInput);

        return Results.Ok(new
        {
            Sentiment = result.PredictedLabel == 1 ? "Postive" : "Negative",
            Confidence = result.Score.Max()
        });
    });

// Run app
app.Run();
